# Generated by Django 3.1.2 on 2021-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='Last_Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
