# Generated by Django 3.1.2 on 2021-02-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='To',
        ),
    ]
