# Generated by Django 3.1.2 on 2021-02-18 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Read_by',
            field=models.ManyToManyField(related_name='read', to=settings.AUTH_USER_MODEL),
        ),
    ]
